### ISSUE TITLE
Move README to README.md

### ISSUE THREAD

**Issue by totemax** [alohl669/local-noip#1]
The readme markdown format isn't parsed by the frontpage because the README file hasn't the markdown extension (.md).

**Comment by totemax** [comment]
Pull request added #2

**Comment by alohl669** [comment]
good good

**Comment by totemax** [comment]
You are a shittyflute. The issue isn't resolved, your Markdown sintax is BAD!!!

**Comment by alohl669** [comment]
Hahahaha my shitty friend, work for me piece of scrap
